### ISSUE TITLE
ODH can't be installed: Startup probe failed: Get "http://172.30.34.41:8080/healthy": dial tcp 172.30.34.41:8080: connect: connection refused

### ISSUE THREAD

**Issue by romeokienzler** [opendatahub-io/opendatahub-operator#150]
**Describe the bug**
ODH can't be installed: Startup probe failed: Get "http://172.30.34.41:8080/healthy": dial tcp 172.30.34.41:8080: connect: connection refused

**To Reproduce**
Steps to reproduce the behavior (create project called odh first):
1.use OS 4.9.17_1525
2. install ODH operator from "stable"
3. Click on create instance
4. change yaml to the following (basically setting namespace to "odh", leave everything else unchanged
```
kind: KfDef
apiVersion: kfdef.apps.kubeflow.org/v1
metadata:
  name: opendatahub
  namespace: odh
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odhseldon/cluster
      name: odhseldon
    - kustomizeConfig:
        parameters:
          - name: SUPERSET_ADMIN_PASSWORD
            value: admin
        repoRef:
          name: manifests
          path: superset
      name: superset
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: openshift-operators
        repoRef:
          name: manifests
          path: kafka/cluster
      name: strimzi-operator
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: kafka/kafka
      name: kafka-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: grafana/cluster
      name: grafana-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: grafana/grafana
      name: grafana-instance
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: radanalyticsio/spark/cluster
      name: radanalyticsio-spark-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: prometheus/cluster
      name: prometheus-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: prometheus/operator
      name: prometheus-operator
    - kustomizeConfig:
        parameters:
          - name: s3_endpoint_url
            value: s3.odh.com
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          - additional
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: airflow/operator
      name: airflow-operator
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: airflow/cluster
      name: airflow-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odhargo/cluster
      name: odhargo-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odhargo/odhargo
      name: odhargo
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
  repos:
    - name: kf-manifests
      uri: >-
        https://github.com/opendatahub-io/manifests/tarball/v1.4.0-rc.2-openshift
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.1.2'

```

**Expected behavior**
ODH full installation should be present

**Screenshots**
![image](https://user-images.githubusercontent.com/5694071/155331794-bdd52c5b-702e-4d67-9515-fc775c472431.png)

**Additional context**
![image](https://user-images.githubusercontent.com/5694071/155331942-e275c54e-9150-401f-9178-e936eaf663b7.png)
