### ISSUE TITLE
Allow opendatahub-operator to read parameters from ENV variables

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#179]
Extend `kfdef.spec.applications.kustomizeConfig.parameters.value` field to read values from environment variables.
For example:

```
  - kustomizeConfig:
      parameters:
        - name: s3_endpoint_url
          value: ${S3_ENDPOINT_URL}
```
 
Support `$VAR` and `${VAR}` syntax.
