### ISSUE TITLE
JupyterHub fails to deploy with 1.4 Operator

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/opendatahub-operator#187]
**Describe the bug**
Resources fail to deploy in ODH 1.4 for legacy JupyterHub

**To Reproduce**
1. Install ODH 1.4 Operator
2. Create a namespace 
3. Deploy the following KFDef:

```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        parameters:
          - name: s3_endpoint_url
            value: s3.odh.com
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/master'
```

Results:

JupyterHub pods will start but a leader will fail to be elected and never goes to a fully ready state.  Eventually the jupyterhub-1-deploy pod will go to a failed state and the rest of the jupyterhub pods will be deleted.

```
oc get pods
NAME                             READY   STATUS      RESTARTS   AGE
jupyterhub-1-4cwrd               1/2     Running     0          4m50s
jupyterhub-1-czlln               1/2     Running     0          4m50s
jupyterhub-1-deploy              1/1     Running     0          4m54s
jupyterhub-1-lzndf               1/2     Running     0          4m50s
jupyterhub-db-1-deploy           0/1     Completed   0          4m54s
jupyterhub-db-1-dm5mb            1/1     Running     0          4m51s
traefik-proxy-7454699d78-2jrc2   2/2     Running     0          4m54s
traefik-proxy-7454699d78-5hjw9   2/2     Running     0          4m54s
traefik-proxy-7454699d78-qvdtb   2/2     Running     0          4m54s
```

The jupyterhub-ha-sidecar container logs show the following error message:

```
E1031 22:57:53.722060 1 leaderelection.go:331] error retrieving resource lock opendatahub/leader-election-lock: leases.coordination.k8s.io "leader-election-lock" is forbidden: User "system:serviceaccount:opendatahub:jupyterhub-hub" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "opendatahub"
```

opendatahub-operator pod shows the following error message:

```
time="2022-10-31T22:56:42Z" level=warning msg="Encountered error applying application jupyterhub:  (kubeflow.error): Code 500 with message: Apply.Run : [roles.authorization.openshift.io \"jupyterhub\" not found, rolebindings.authorization.openshift.io \"jupyterhub\" not found]"
```

The jupyterhub role referenced in the above error message is still located in the repo here:

https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/jupyterhub/base/jupyterhub-role.yaml

And is referenced in the kustomize file here:

https://github.com/opendatahub-io/odh-manifests/blob/bd8cfa9a95e05be18b213f249b62f5a2858aa212/jupyterhub/jupyterhub/base/kustomization.yaml#L13

**Expected behavior**
Operator should successfully deploy the jupyterhub role which will enable the completion of the JupyterHub instance.

**Screenshots**

**Additional context**
This was tested on a brand new 4.10 cluster from RHPDS.

For additional validation I uninstalled 1.4 from my cluster and installed 1.3 using the following subscription:

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: opendatahub-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Manual
  name: opendatahub-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: opendatahub-operator.v1.3.0
```

After manually approving the `installplan` I installed the same KFDef referenced above and everything deploys successfully.
