### ISSUE TITLE
Reduce the scope of the clusterpermissions required by the operator

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/opendatahub-operator#23]
As of the 0.6 release the operator now request cluster-admin permissions.  We should reduce the scope of the permissions requested to clearly state what cluster permissions are required to run the ODH operator.

**Comment by maulikjs** [comment]
As of ODH 0.9.0

Heres the output of the audit2rbac tool which deploys all the ODH components, we can use this as a starting point.

**Comment by maulikjs** [comment]
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.8.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-openshift-operators-opendatahub-operator
  name: audit2rbac:system:serviceaccount:openshift-operators:opendatahub-operator
  namespace: dh-temp
rules:
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - authorization.openshift.io
  resourceNames:
  - jupyterhub
  resources:
  - rolebindings
  verbs:
  - get
- apiGroups:
  - authorization.openshift.io
  resourceNames:
  - jupyterhub
  resources:
  - roles
  verbs:
  - create
  - get
- apiGroups:
  - image.openshift.io
  resourceNames:
  - s2i-minimal-notebook
  resources:
  - imagestreams
  verbs:
  - create
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resourceNames:
  - jupyterhub
  resources:
  - routes
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resourceNames:
  - superset
  resources:
  - routes
  verbs:
  - delete
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.8.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-openshift-operators-opendatahub-operator
  name: audit2rbac:system:serviceaccount:openshift-operators:opendatahub-operator
  namespace: dh-temp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: audit2rbac:system:serviceaccount:openshift-operators:opendatahub-operator
subjects:
- kind: ServiceAccount
  name: opendatahub-operator
  namespace: openshift-operators
```
