### ISSUE TITLE
Update Network Policies to allow access to required services.

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#423]
The DSCInitialization controller creates network policy that [allows all ](https://github.com/opendatahub-io/opendatahub-operator/blob/main/controllers/dscinitialization/utils.go#L180)traffic in ODH namespaces .

Update the Networkpolicy to allow all traffic only between ODH namespaces(with label opendatahub.io/generated-namespace='true') 

```
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              opendatahub.io/generated-namespace: 'true'
  policyTypes:
    - Ingress
```

Acceptance Criteria

- Creates updated Networkpolicy that allows all traffic between ODH namespaces
- Verify all components work as expected
