### ISSUE TITLE
Inconsistent default DSCs for different methods of creation

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/opendatahub-operator#428]
**Describe the bug**
When using different methods for creating the DSC, the default YAML object changes what the user is presented.

**To Reproduce**
When using the `Create DataScienceCluster` button on the DSC tab or the `Create instance` button on the details tab

![image](https://github.com/opendatahub-io/opendatahub-operator/assets/1628206/56967174-b256-40b0-b607-ec0ac82cecb3)

The following object is auto populated:

```yaml
kind: DataScienceCluster
apiVersion: datasciencecluster.opendatahub.io/v1alpha1
metadata:
  labels:
    app.kubernetes.io/created-by: opendatahub-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/part-of: opendatahub-operator
  name: default
spec:
  components:
    dashboard:
      enabled: false
    datasciencepipelines:
      enabled: false
    distributedworkloads:
      enabled: false
    kserve:
      enabled: false
    modelmeshserving:
      enabled: false
    workbenches:
      enabled: false
```

When using the `Create DataScienceCluster` button on the `DataSciecneCluster required` section of the details tab

![image](https://github.com/opendatahub-io/opendatahub-operator/assets/1628206/cf5db453-0a5f-4339-8828-2e91e9578806)

The following object is auto populated:

```yaml
kind: DataScienceCluster
apiVersion: datasciencecluster.opendatahub.io/v1alpha1
metadata:
  name: default
spec: {}
```

**Expected behavior**
Using both options I would expect the object to auto-populate to something like this:

```yaml
kind: DataScienceCluster
apiVersion: datasciencecluster.opendatahub.io/v1alpha1
metadata:
  name: default
spec:
  components:
    dashboard:
      enabled: true
    datasciencepipelines:
      enabled: true
    distributedworkloads:
      enabled: true
    kserve:
      enabled: true
    modelmeshserving:
      enabled: true
    workbenches:
      enabled: true
```

**Screenshots**

**Additional context**
In previous discussion we have talked about the idea that all of the components should be enabled as true by default, and allow the users to turn off things that they don't want.  By enabling everything by default we are giving new users a default configuration that will allow them to explore all of the components and they can choose to remove components as needed at a later time.
