### ISSUE TITLE
Enable components by default 

### ISSUE THREAD

**Issue by ldimaggi** [opendatahub-io/opendatahub-operator#432]
**Describe the bug**
After installing the new operator, the user must manually (editing YAML) to enable these coomponents:

 ```
 components:
    codeflare:
      enabled: false
    dashboard:
      enabled: false
    datasciencepipelines:
      enabled: false
    kserve:
      enabled: false
    modelmeshserving:
      enabled: false
    ray:
      enabled: false
    workbenches:
      enabled: false
```

https://github.com/opendatahub-io/opendatahub-operator/blob/feature-rearchitecture/config/samples/datasciencecluster_v1alpha1_datasciencecluster.yaml#L12

My guess is that some users will not understand that they have the extra step of editing the YAML - why not have these components enabled by default?

**To Reproduce**
1. Install the opeator - hand edit the YAML

**Expected behavior**
From a user's perspective, installing the operator in the UI would be the only step needed.
