### ISSUE TITLE
Update operator resource requests/limits

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/opendatahub-operator#578]
**Is your feature request related to a problem? Please describe.**
Currently the operator sets the following resources:

```
        resources:
          limits:
            cpu: 500m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 256Mi
```

https://github.com/opendatahub-io/opendatahub-operator/blob/f1dddc1fc0489dccc3ba349760a40b2e13914e1d/config/manager/manager.yaml#L63

These resource requests and limits seem extremely high.

**Describe the solution you'd like**
Since the operator is only expecting to manage the dsc-init and dsc objects and the expectation is that only a single instance of those objects will exist on any cluster we should not expect to need to "scale" and we can set reasonable requests/limits based on the observed utilization of the operator.

**Describe alternatives you've considered**
The Vertical Pod Autoscaler includes a recommender mode that allows you to track the cpu/memory usage of a deployment and VPA will create recommendation over the course of several days.

I have used VPA recommender with great success at customers that are deploying hundreds of pods and processing thousands of transactions per hour with great success.  

**Additional context**
