### ISSUE TITLE
Adding both Kubeflow and Open data hub manifests will not work

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/opendatahub-operator#6]
If we want to install both Open Data Hub and Kubeflow components at the same time, we need to make these changes
1. kfdef file needs to specify "kubeflow" as namespace
```
apiVersion: kfdef.apps.kubeflow.org/v1beta1
kind: KfDef
metadata:
  name: opendatahub
  namespace: kubeflow
```
2. Include namespace creation to odh-common 
3. Add namespace: opendatahub to all ODH components. If we don't do this then some components got installed in Kubeflow namespace
4. Include two uri's at the bottom of kfDef resource with different manifest names. Use the two different names accordingly in the component description.

Note: Including opendatahub as the main namespace will get all Kubeflow components installed in opendatahub namespace with some components not working, example KF portal cannot find profile controller.
