### ISSUE TITLE
kfdef file requires a repo called `manifests`

### ISSUE THREAD

**Issue by anishasthana** [opendatahub-io/opendatahub-operator#64]
The following kfdef file does not work
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  annotations:
    kfctl.kubeflow.io/force-delete: 'false'
  name: opendatahub
  namespace: odh-deployment
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: odh-manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        parameters:
          - name: s3_endpoint_url
            value: s3.odh.com
        repoRef:
          name: odh-manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          - additional
        repoRef:
          name: odh-manifests
          path: jupyterhub/notebook-images
      name: notebook-images
  repos:
    - name: odh-manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v0.8.0'
    - name: custom-manifests
      uri: 'https://github.com/anishasthana/odh-manifests/tarball/test_foo'
  version: v0.8.0
```

Changing the name of one of the repos to be `manifests` fixes the issue that was popping up.

The relevant error logs:
```

time="2020-09-28T20:44:56Z" level=error msg="failed to build kfApp from URI /tmp/odh-deployment/opendatahub/config.yaml: Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: Kustomize generate failed: Repo manifests not listed in KfDef.Status; ."
time="2020-09-28T20:44:56Z" level=error msg="Failed to load KfApp. Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: Kustomize generate failed: Repo manifests not listed in KfDef.Status; ."
```
