### ISSUE TITLE
DSC & Dashboard Inconsistencies

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/opendatahub-operator#641]
**Describe the bug**
DSC Status vs DSC Spec. "odh-dashboard"?

In the Spec, Dashboard is referred to as "dashboard".
In the Status, Dashboard is referred to as "odh-dashboard".

Any reason why this is the case?

```
  installedComponents:
    codeflare: false
    data-science-pipelines-operator: false
    kserve: false
    model-mesh: false
    odh-dashboard: true
    ray: false
    workbenches: false
```
One of these things is not like the others... any reason why we are called 'odh-dashboard' and not just 'dashboard'?

**To Reproduce**
1. Go to DSC
2. View YAML

**Expected behavior**
Name Dashboard the same as other components.

**Screenshots**
<img width="539" alt="image" src="https://github.com/opendatahub-io/opendatahub-operator/assets/8126518/ee36874b-5eff-4ddb-a035-1d8bbf651763">

**Additional context**
