### ISSUE TITLE
Add Trusty AI component

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#671]
Extend the DSC api to include TrustyAI as a component. This component will be responsible for deployment of trustyai-operator.

**Additional Details**
Expected DSC CR:

```
spec:
  components:
    trustyai:
      managementState: "Managed"
```

TrustyAI Manifests: https://github.com/trustyai-explainability/trustyai-service-operator
