### ISSUE TITLE
Allow image updates using DSC

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#673]
Extend DSC component api to expose `image` field for every controller in a component.

**Additional context**
An example dsc would look like - 
```
spec:
  components:
     workbenches:
          notebookController:
               image: <>
          kfNotebookController:
                image: <>
```
