### ISSUE TITLE
cannot override notebook controller and odh notebook controller deployment via DataScienceCluster

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/opendatahub-operator#719]
**Describe the bug**
latest v2 operator version

DataScienceCluster spec:

```
spec:
  components:
    codeflare:
      devFlags: {}
      managementState: Removed
    dashboard:
      devFlags:
        manifests:
          - contextDir: odh-dashboard
            sourcePath: base
            uri: >-
              https://repo.com/artifactory/intern/odh-manifests.tar.gz
      managementState: Managed
    datasciencepipelines:
      devFlags: {}
      managementState: Removed
    kserve:
      devFlags: {}
      managementState: Removed
    modelmeshserving:
      devFlags: {}
      managementState: Removed
    ray:
      devFlags: {}
      managementState: Removed
   trustyai:
      devFlags: {}
    workbenches:
      devFlags:
        manifests:
          - contextDir: odh-notebook-controller
            sourcePath: base
            uri: >-
              https://repo.com/artifactory/intern/odh-manifests.tar.gz
          - contextDir: notebook-images
            sourcePath: overlays/additional
            uri: >-
              https://repo.com/artifactory/intern/odh-manifests.tar.gz
      managementState: Managed
```

Imagestreams (notebooks) and odh dashboard are applied from the custom repo location. However, odh notebook controller and kubeflow notebook controller are not.

**To Reproduce**

in v2 operator: I am trying to apply own odh-notebook-controller and kubeflow-notebook-controller manifests.

It does not work. kubeflow notebook controller and odh notebook contoller always come from quay.io/opendatahub/

Regardless of what I do, notebook-controller-deployment and odh-notebook-controller-manager deployment are always pulled from some location on the public internet.

is odh-notebook-controller and its associated kubeflow notebook controller part of DataScienceCluster component: workbenches? 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by VaishnaviHire** [comment]
Hi @shalberd , would you be able to share the folder structures for your notebook manifests?

**Comment by zdtsw** [comment]
i am thinking, since the logic of using overriden manifests for notebook images is very much upon the value of [ContextDir](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/components/workbenches/workbenches.go#L57) it might not work if you have a different folder in your tarball.

**Comment by shalberd** [comment]
Here are the folders:
![Bildschirmfoto 2023-11-10 um 09 32 01](https://github.com/opendatahub-io/opendatahub-operator/assets/21118431/1e09e616-fa70-428a-8a09-5b4ccaa898fc)
![Bildschirmfoto 2023-11-10 um 09 32 22](https://github.com/opendatahub-io/opendatahub-operator/assets/21118431/3bfe2283-f911-4993-986d-c9b3d1079f5f)

**Comment by shalberd** [comment]
@zdtsw I don't know, I cannot get this to work successfully with a link
https://repo.com/artifactory/intern/odh-manifests.tar.gz

in my view, contextDir should be the first dir under the untarred file.
And sourcePath should be the path to the folder containing the default kustomization.yaml.

The logic in the file you mentioned is full of ifs, conditional compares of url string matches, and so on. I find that almost impossible to adopt.

**Comment by shalberd** [comment]
basically, with notebook-images, for
contextDir: notebook-images the manifests[x].uri needs to have "notebooks" anywhere in the uri, which is not good.

for odh notebook controller and kubeflow notebook controller, I am still trying out.

**Comment by zdtsw** [comment]
Sorry for late reply!

I agree with you, the logic of using DevFlags in workbench is more complex than other components but this is also due to the fact that workbench need to deal with : notebook images and 2 different NBC.
- for notebook image, we use `uri` to do match
- for nbc, we use `contextDir` to do match

```
workbenches:
      devFlags:
        manifests:
          - contextDir: odh-notebook-controller            # here keyword  is "components/odh-notebook-controller"
            sourcePath: base                                              # correct value or you can even skip it in your case
            uri: >-
              https://repo.com/artifactory/intern/odh-manifests.tar.gz
          - contextDir: notebook-images                                                    # does not really matter the value for notebook here
            sourcePath: overlays/additional                                                # correct value or you can even skip it in your case
            uri: >-
              https://repo.com/artifactory/intern/odh-manifests.tar.gz  # here you need to include keyword "notebooks"
      managementState: Managed
```
