### ISSUE TITLE
Add Model Registry component

### ISSUE THREAD

**Issue by dhirajsb** [opendatahub-io/opendatahub-operator#775]
**Is your feature request related to a problem? Please describe.**
Extend the DSC api to include ModelRegistry as a component. This component will be responsible for deployment of model-registry-operator.

**Describe the solution you'd like**
Expected DSC CR to enable ModelRegistry (`Removed` by default in samples):
```
spec:
  components:
    modelregistry:
      managementState: "Managed"
```
**Describe alternatives you've considered**
None

**Additional context**
ModelRegistry Manifests: https://github.com/opendatahub-io/model-registry-operator
