### ISSUE TITLE
Issues with workbenches & devFlags

### ISSUE THREAD

**Issue by BlueCog** [opendatahub-io/opendatahub-operator#780]
I'm attempting to air-gap `odh-2.4.0`. The operator is operational, and now I'm trying to air-gap the various components using devFlags.

So far, I've successfully air-gapped `dashboard` and `datasciencepipelines` without any problems:

```
    dashboard:
      devFlags:
        manifests:
          - contextDir: components/dashboard
            sourcePath: base
            uri: >-
              https://repo.com/repository/opendatahub/odh-manifests.tar.gz
    datasciencepipelines:
      devFlags:
        manifests:
          - contextDir: components/data-science-pipelines-operator
            sourcePath: base
            uri: >-
                https://repo.com/repository/opendatahub/odh-manifests.tar.gz
```
Now, I'm moving on to `workbenches`, but I'm encountering some troubles...

I've followed this function:
https://github.com/opendatahub-io/opendatahub-operator/blob/odh-2.4.0/components/workbenches/workbenches.go#L33

I've also reviewed older incidents, like: https://github.com/opendatahub-io/opendatahub-operator/issues/719, which provided more details. However, the `base` folder in `odh-notebook-controller` seems to have been removed in newer versions.

Here is the relevant part of my data science cluster YAML for `workbenches`:
```
    workbenches:
      devFlags:
        manifests:
          - contextDir: components/odh-notebook-controller           
            uri: >-
              https://repo.com/repository/opendatahub/odh-manifests.tar.gz
          - contextDir: components/notebook-controller                                    
            uri: >-
              https://repo.com/repository/opendatahub/odh-manifests.tar.gz
          - contextDir: components/notebook-images                                                    
            sourcePath: overlays/additional                                                
            uri: >-
              https:///repo.com/repository/opendatahub/notebooks-manifests.tar.gz
      managementState: Managed
```

The folder structure of `odh-manifests.tar.gz` is: `odh-manifests/components/odh-notebook-controller`

I've edited the `kustomization.yaml` files to reflect the air-gapped images. `Base` for `odh-notebook-controller` and `overlays/openshift` for `kf-notebook-controller`. Some offline testing, like `kustomize build . | grep image:`, is successful.

However, the `kustomization.yaml` is not being applied. Also, when I check the local file system at `/opt/manifests/odh-notebook-controller/` of the operator, the `kustomization.yaml` is the default one, not the custom one I've edited and hosted at `odh-manifests.tar.gz`.

I've tried multiple scenarios:

- with or without `sourcePath`
- Different `contextDir` (but the function seems specific to this).
- Restarting the operator (to flush any local data).
- Removing the components folder from the `tar.gz` (which seems not to matter for the function).
- Editing all the `kustomization` files and deployments.
...

At one point, I was successful in editing `odh-notebook-controller`, but I never had a working scenario for `kf-notebook-controller`.

Did I miss something?

_P.S. It would be helpful if the operator logged some failures or issues with devFlags._
